<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAyKMOhe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAyKMOhe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAyKMOhe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAyKMOhe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAyKMOhe\App_KernelDevDebugContainer([
    'container.build_hash' => 'AyKMOhe',
    'container.build_id' => '04400ddc',
    'container.build_time' => 1677066753,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAyKMOhe');
