<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR9KgXEk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR9KgXEk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR9KgXEk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR9KgXEk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR9KgXEk\App_KernelDevDebugContainer([
    'container.build_hash' => 'R9KgXEk',
    'container.build_id' => 'e157bd66',
    'container.build_time' => 1677080769,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR9KgXEk');
